-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-bounce_records-br_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  bounce_records ALTER br_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE  bounce_records ALTER br_timestamp
DROP  DEFAULT;
ALTER TABLE  bounce_records ALTER br_timestamp TYPE TIMESTAMPTZ;