-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BounceHandler/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bounce_records (
  br_id SERIAL NOT NULL,
  br_user_email VARCHAR(255) NOT NULL,
  br_timestamp TIMESTAMPTZ NOT NULL,
  br_reason VARCHAR(255) NOT NULL,
  PRIMARY KEY(br_id)
);

CREATE INDEX br_mail_timestamp ON bounce_records (br_user_email, br_timestamp);

CREATE INDEX br_timestamp ON bounce_records (br_timestamp);
